services:
  djangoserver:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env

    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=company_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=motasem
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: redis

  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    container_name: celery
    build: .
    command: celery -A company_management worker -l INFO
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=company_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=motasem
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - db


  tailwind:
    container_name: tailwind
    build:
      context: ./frontend
    working_dir: /app/frontend
    volumes:
      - .:/app
      - tailwind_node_modules:/app/frontend/node_modules
    command: npm run watch

volumes:
  postgres_data:
  tailwind_node_modules:
  media_volume: