# Generated by Django 6.1.1 on 2026-09-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'pedning'), (2, 'delivered'), (3, 'failed')], default=1),
        ),
    ]
