# Generated by Django 6.1.1 on 2026-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletterhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
