# Generated by Django 6.1.1 on 2026-09-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_image_newsletter_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='uploaded_file',
        ),
    ]
