# Generated by Django 6.1.1 on 2026-10-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_remove_newsletter_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='image',
        ),
    ]
