# Generated by Django 6.1.1 on 2026-09-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_postlike_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
