# Generated by Django 6.1.1 on 2026-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'drafted'), (2, 'pending_update'), (3, 'rejected'), (4, 'published')], default=1),
        ),
    ]
