# Generated by Django 6.1.1 on 2026-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_is_published_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'drafted'), (2, 'rejected'), (3, 'published')], default=1),
        ),
    ]
