# Generated by Django 6.1.1 on 2026-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'drafted'), (2, 'pending_update'), (3, 'rejected'), (4, 'published')], default=1),
        ),
    ]
