# Generated by Django 6.1.1 on 2026-09-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='post',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='project',
        ),
        migrations.AddField(
            model_name='approval',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='approval',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
