# Generated by Django 6.1.1 on 2026-09-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_remove_approval_post_remove_approval_project_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('content_type', 'object_id')},
        ),
    ]
