# Generated by Django 6.1.1 on 2026-09-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_alter_approval_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
