# Generated by Django 6.1.1 on 2026-10-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_approval_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='procedure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'approved'), (3, 'rejected'), (4, 'cancelled')], default=1),
        ),
    ]
