# Generated by Django 6.1.1 on 2026-10-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_approval_procedure_alter_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='procedure',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
