# Generated by Django 6.1.1 on 2026-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_alter_approval_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='procedure',
            field=models.IntegerField(null=True),
        ),
    ]
