# Generated by Django 6.1.1 on 2026-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_alter_approval_order_alter_approval_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='proposed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
