# Generated by Django 6.1.1 on 2026-10-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0008_approval_proposed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='proposed_data',
        ),
    ]
