# Generated by Django 6.1.1 on 2026-10-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0009_remove_approval_proposed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='updated_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
