# Generated by Django 6.1.1 on 2026-09-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_manage_project', 'can manage a project')]},
        ),
    ]
