# Generated by Django 6.1.1 on 2026-09-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_update_project', 'can update a project')]},
        ),
    ]
