# Generated by Django 6.1.1 on 2026-09-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_manage_project', 'can manage a project')]},
        ),
    ]
