# Generated by Django 6.1.1 on 2026-09-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_manage_project', 'can manage a project'), ('can_edit_project_status', 'can edit a status of a project'), ('can_write_note', 'can write a note to a project')]},
        ),
    ]
