# Generated by Django 6.1.1 on 2026-09-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
