# Generated by Django 6.1.1 on 2026-09-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_task_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_create_blog', 'can_create a category in a blog')]},
        ),
    ]
