# Generated by Django 6.1.1 on 2026-10-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'in progress'), (3, 'under review'), (4, 'cancelled'), (5, 'completed')], default=1),
        ),
    ]
